### PR TITLE
Ignored generated file

### PR DESCRIPTION
**Pull request by odahcam**
`composer.lock` is a Composer generated file and should be ignored.

### CODE REVIEW

**Comment by ocram** [comment]
Thanks!

While `composer.lock` is auto-generated, and most auto-generated files should normally be ignored, that file is here for a reason.

It locks the version of all dependencies to a known state and ensures that everybody (including your future self) is working with the same setup.

See also: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by odahcam** [comment]
Yw, but why not just set the version in compser.json?

**Comment by ocram** [comment]
In `composer.json`, you set version *constraints* only, e.g. `^2.1` (which means 2.1+ but below 3.0). Then, `composer.lock` may *additionally* be used to set *exact* versions, e.g. `2.3.7`. For more information, please refer to the Composer documentation, e.g. [here](https://getcomposer.org/doc/articles/versions.md).

**Comment by odahcam** [comment]
I can't test now, but I think you can define the exact version you want in `composer.json`, like in npm's `package.json`.

**Comment by ocram** [comment]
You can, but you usually don't want that. The two files `composer.json` and `composer.lock` are for different purposes, and the latter is optional to use (and optional to check into version control). Feel free *not* to use it, but in this project, we'll continue to utilize it.

**Comment by odahcam** [comment]
Okay, thx for clarifying things up. :)

**Pull request closed without merging**
