### PR TITLE
Update Auth.php

### PR DESCRIPTION
**Pull request by darkalchemy**
Set setSameSiteRestriction param in setRememberCookie() when php version is 7.3 or greater.

### CODE REVIEW

**Comment by ocram** [comment]
Thanks!

You’re probably thinking of `setcookie`, which accepts sets of additional attributes (including `SameSite`) since 7.3. But we’re not using `setcookie` here.

This library here uses a [separate cookie library](https://github.com/delight-im/PHP-Cookie) that supports `SameSite` on *all* PHP versions, and we have been setting that attribute for quite some time already.

**Comment by darkalchemy** [comment]
Thanks for your reply. 

Maybe I'm missing something because it get set with my changes but doesn't without them. 

Would you please confirm. 

Thanks again

**Comment by ocram** [comment]
Oh, that’s probably correct, but it’s another issue.

Where did you actually set it to `Strict` and expect a change? I’m not sure this library offers any option where you can change it. So where did you pass or set `Strict`?

The ability to provide `Strict` (or even disable `SameSite` restrictions again) is planned and tracked [in this other issue](https://github.com/delight-im/PHP-Auth/issues/120).

**Comment by darkalchemy** [comment]
I have a file that sets up my session variables with ini_set and those are picked up in $params and passed to the cookie class. If I don't add  setSameSiteRestriction to params, it doesn't get passed and the default 'Lax' is set in the cookie. 

I hope that makes sense.

**Comment by ocram** [comment]
Ah, so you’re setting `session.cookie_samesite` in `php.ini` (which can be either the empty string, or `Lax`, or `Strict`) and expecting that value to be reflected, right?

**Comment by darkalchemy** [comment]
That is correct.

**Pull request closed without merging**
