### PR TITLE
Added PostgreSQL script for creating tables.

### PR DESCRIPTION
**Pull request by chibicitiberiu**
I am using PostgreSQL for my site, so I had to modify the existing script to run on PostgreSQL. I thought it would be nice to share the script.

### CODE REVIEW

**Comment by ocram** [comment]
Definitely appreciated, thank you very much!

As someone who is more experienced with PostgreSQL than we are, can you comment on the existing proposal in https://github.com/delight-im/PHP-Auth/issues/65 and the differences to your proposal, especially with regard to the sequences and constraints?

**Comment by chibicitiberiu** [comment]
Hi. I didn't see the issue when I made the pull request, sorry about that.

Looking at the proposed schema, the main difference is that it is generated using pg_dump (equivalent to the MySQL database dump functionality), while this pull request is made by converting from the MySQL schema:

- the SET instructions are generated by pg_dump, probably to make sure that a differently configured PostgreSQL server can run the script without any issues (MySQL does something similar)
- the SERIAL data type I used for primary keys is basically an autoincrement integer. When using a SERIAL datatype, PostgreSQL actually does the same thing that can be seen in the pg_dump (creates a sequence, and sets default to nextval(sequence)).
- VARCHAR is an alias of CHARACTER VARYING, so they mean the same thing
- CREATE INDEX... USING 'btree' - btree is the default indexing method

The only difference I see (other than differences that appear between a database dump and the create scripts), is that I didn't use those constraints. PostgreSQL doesn't have unsigned integer types, so those constraints were added to enforce the values being positive. If you consider this necessary, I can add it.

**Comment by ocram** [comment]
No problem!

Thanks again for your contribution, and for explaining the differences between the two proposals, which has been very helpful.

Your definitions have been merged in https://github.com/delight-im/PHP-Auth/commit/2f9bab47790466aa04f60d47478c104bd02cef2c.

On top of your proposal, I have applied three minor changes in the following commit: https://github.com/delight-im/PHP-Auth/commit/1121685cef0cf25a49cc6e3e1b3154e5c82dc468

These modifications are:

 * I’ve dropped the explicit index on the `users.email` column. As far as I understand, the `UNIQUE` constraint does already create an *implicit* index, so the explicit one is redundant and may even double the space usage for what we want here. Apart from that, you didn’t add an explicit index for the other three `UNIQUE` columns, so you seem to agree.
 * The `PRIMARY KEY` for the `users_throttling.bucket` column should imply the `NOT NULL`. Again, you seem to agree, judging from the four other `PRIMARY KEY` columns.
 * In MySQL, the type `FLOAT` has been used for the `users_throttling.tokens` column. In PostgreSQL this exists as well, but corresponds to `DOUBLE PRECISION`, as per my research, instead of the `REAL` that we want here (which has only half the precision – and space consumption).

Finally, the check constraints for simulating unsigned values have been added: https://github.com/delight-im/PHP-Auth/commit/62d9e44aa4dda6f6881f335753020575a818074b Of course, these are not really necessary, but still good to have for portability and compatibility with MySQL, and simply for documentation purposes.

Once again, thank you very much!

**Comment by akwatra** [comment]
need to modify the column in table users_remembered
user_id integer NOT NULL, user integer NOT NULL,
in above mention sql.

I have created a repo for Postgres SQL dump with bove correction.
https://github.com/akwatra/delight-im_php-auth-postgres

**Comment by chibicitiberiu** [comment]
Your assumptions are correct.
Glad I could contribute 👍 .

Another improvement could be adding foreign keys. I assume they weren't added in the MySQL and the SQLite scripts because the storage engines don't support foreign keys.

**Comment by ocram** [comment]
Yes, that’s correct. In MySQL, support for foreign keys depends on the storage engine that is used. For maximum compatibility, foreign keys had thus not been added. And now, in PostgreSQL, we can’t add them right now because we want to preserve compatibility with MySQL. But we should definitely think about foreign keys again, and discuss whether adding them now makes more sense than going without. Luckily, with the given schema, foreign keys are not *that* important because the columns affected and thus the advantages are limited.

**Comment by chibicitiberiu** [comment]
As this is a different topic, I created issue #86 for further discussion.

**Pull request closed without merging**
